### ISSUE TITLE
8184.7 DEV add columns to systemConfigs table

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#10]
- https://github.com/Shippable/pm/issues/8184
- add all the new columns defined in linked PM issue to systemConfigs table
- the systemConfigs.sql.template file should be updated with required migrations

**Comment by stephanielingwood** [comment]
1. add column in `systemConfigs` table to store the bootstrap status of installer
```
    isBootstrapped: {
      type: Sequelize.Boolean,
      field: 'isBootstrapped',
      allowNull: false,
      defaultValue: false
    },
```
1. add column in `systemConfigs` table to store ecr keys used by installer
```
    accessKey: {
      type: Sequelize.STRING(255),
      field: 'accessKey',
      allowNull: false
    },
    secretKey: {
      type: Sequelize.STRING(255),
      field: 'secretKey',
      allowNull: false
    },
```
1. add column in `systemConfigs` table to store release
```
    release: {
      type: Sequelize.STRING(24),
      field: 'release',
      defaultValue: 'master',
      allowNull: false
    },
```
1. add column in `systemConfigs` table to store services information. This will be json-stringified information(replicas, mounts, docker options etc) of all the running services (api, www, sync etc) 
```
   services: {
      type: Sequelize.TEXT,
      get: function() {
        var services = this.getDataValue('services');
        if (!_.isEmpty(services))
          services = JSON.parse(services);
        return services;
      },
      set: function(val) {
        if (_.isObject(val))
          val = JSON.stringify(val);
        this.setDataValue('services', val);
      }
    }
```
1. add column in `systemConfigs` table to store db information. this is json-stringified version of db information (machine IP, ports exposed, login user, install status, initialize status etc)
```
db: {
      type: Sequelize.TEXT,
      get: function() {
        var db = this.getDataValue('db');
        if (!_.isEmpty(db))
          pb = JSON.parse(db);
        return db;
      },
      set: function(val) {
        if (_.isObject(val))
          val = JSON.stringify(val);
        this.setDataValue('db', val);
      }
    }
```
1. add column in `systemConfigs` table to store rabbitmq information. this is json-stringified version of rabbitmq information (machine IP, ports exposed, login user, install status, initialize status etc)
```
msg: {
      type: Sequelize.TEXT,
      get: function() {
        var msg = this.getDataValue('msg');
        if (!_.isEmpty(msg))
          pb = JSON.parse(msg);
        return msg;
      },
      set: function(val) {
        if (_.isObject(val))
          val = JSON.stringify(val);
        this.setDataValue('msg', val);
      }
    }
```
1. add column in `systemConfigs` table to store gitlab information. this is json-stringified version of gitlab information (machine IP, ports exposed, login user, install status, initialize status etc)
```
state: {
      type: Sequelize.TEXT,
      get: function() {
        var db = this.getDataValue('state');
        if (!_.isEmpty(state))
          pb = JSON.parse(state);
        return state;
      },
      set: function(val) {
        if (_.isObject(val))
          val = JSON.stringify(val);
        this.setDataValue('state', val);
      }
    }
```
1. add column in `systemConfigs` to store vault information. this is json-stringified version of vault information (machine IP, ports exposed, login user, install status, initialize status etc)
```
secrets: {
      type: Sequelize.TEXT,
      get: function() {
        var secrets = this.getDataValue('secrets');
        if (!_.isEmpty(secrets))
          secrets = JSON.parse(secrets);
        return secrets;
      },
      set: function(val) {
        if (_.isObject(val))
          val = JSON.stringify(val);
        this.setDataValue('secrets', val);
      }
    }
```
1. add column in `systemConfigs` to store redis information. this is json-stringified version of redis information (machine IP, ports exposed, login user, install status, initialize status etc)
```
redis: {
      type: Sequelize.TEXT,
      get: function() {
        var redis = this.getDataValue('redis');
        if (!_.isEmpty(redis))
          redis = JSON.parse(redis);
        return redis;
      },
      set: function(val) {
        if (_.isObject(val))
          val = JSON.stringify(val);
        this.setDataValue('redis', val);
      }
    }
```
1. add column in `systemConfigs` to store swarm master information. this is json-stringified version of swarm master information (machine IP, ports exposed, login user, install status, initialize status etc)
```
master: {
      type: Sequelize.TEXT,
      get: function() {
        var master = this.getDataValue('master');
        if (!_.isEmpty(master))
          master = JSON.parse(master);
        return master;
      },
      set: function(val) {
        if (_.isObject(val))
          val = JSON.stringify(val);
        this.setDataValue('master', val);
      }
    }
```
1. add column in `systemConfigs` to store information about swarm workers. this is json-stringified version of swarm workers information (machine IPs, ports exposed, login user, install status, initialize status etc)
```
workers: {
      type: Sequelize.TEXT,
      get: function() {
        var workers = this.getDataValue('workers');
        if (!_.isEmpty(workers))
          workers = JSON.parse(workers);
        return workers;
      },
      set: function(val) {
        if (_.isObject(val))
          val = JSON.stringify(val);
        this.setDataValue('workers', val);
      }
    }
```
