### ISSUE TITLE
Push v5.9.3 to Amazon marketplace

### ISSUE THREAD

**Issue by rageshkrishna** [Shippable/admiral#1093]
- a new ami needs to be published on the marketplace for version v5.9.2
- chageset: https://github.com/Shippable/support/wiki/5.9.2
- ami id: `ami-52cd2928`

**Comment by ttrahan** [comment]
@avinci : my password to the AWS Prod account, where this is submitted, has expired. I need you to re-enable it for user 'prod-tom'

**Comment by ttrahan** [comment]
@avinci : still need the prod account access for 'prod-tom' extended

**Comment by avinci** [comment]
I have sent the password to you

**Comment by avinci** [comment]
i think we should wait until next weeks release to do this. There are more perf changes that are going in....

**Comment by ttrahan** [comment]
Closing this until the next release.

**Comment by ttrahan** [comment]
This is in process now with AWS Marketplace for v5.9.4

**Comment by ttrahan** [comment]
Have switched this to v5.9.3. In process.
