### ISSUE TITLE
8184.1 DEV add route to initialize vault

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#11]
- https://github.com/Shippable/pm/issues/8184
- add route `POST /api/vault/` to initialize vault container. 
- the handler should run the corresponding vault initialization script on local machine to bring up vault server
- vault should boot with persistent data mounts

**Comment by stephanielingwood** [comment]
1. **Vault Configuration**
  - once vault is installed, create vault table on db
  - update vault config file with database ip, user and password
  - start vault service and bootstrap it 
  - copy the vault root key from remote and update it in database
  - copy the generated vault token from remote machine to local `/etc/shippable/vault/` directory
  - update the vault token into system config in db
  - set the status of machine in `systemConfigs.secrets.isInitialized=true`
  - the UI should look like following for the init page
  - logs should be tailed from a logfile in `logs` tab
