### ISSUE TITLE
8184.11 DEV show page to initialize vault

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#12]
- https://github.com/Shippable/pm/issues/8184
- show a page on admiral UI to initialize vault on local machine
- the heap contains mockup of how this page should look like
- once vault is initialized, show the vault token, unlock keys and ip address
- if vault server is not reachable show error

**Comment by a-murphy** [comment]
Update from Devashish:
- add vault view page. clicking on vault button should open this page
     - check if vault is initialized and installed or not
     - if not, then show button to initialize vault
     - clicking button should call POST /vault route with no params

**Comment by stephanielingwood** [comment]
from the heap:

1. **Vault Installation**
  - the `Vault` tab opens the configuration for setting up vault store
  - ask whether to run vault as container on local machine or configure an existing vault installation
  - call `POST /vault/` to initialize vault
  - if first option is selected, then run docker command to bring up vault
      - mount all the configs in `/etc/shippable/vault:/etc/shippable/vault.d/`
      - mount the logs in `/var/run/shippable/vault/logs/:/var/logs/vault/`
  - logs should be tailed from a logfile in `logs` tab

**Comment by a-murphy** [comment]
The UI works properly now, and I've figured out the first Docker errors, but haven't found a way around
```
docker: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory
```
when trying to start Vault.

**Comment by stephanielingwood** [comment]
closing. moved to new pm.
