### ISSUE TITLE
8312.7 Check that core services aren't being re-initialized

### ISSUE THREAD

**Issue by stephanielingwood** [Shippable/admiral#124]
Shippable/pm#8312

The logic should already be in place. Verify that, when `/api/initialize` is called, the vault, rabbit, gitlab, and redis POST routes aren't being called if they are already initialized (as determined by the result of the GET call).

**Comment by trriplejay** [comment]
verified by repeatedly clicking intiailzie in the UI. the post DB does a lot of stuff each time (create dirs, run migrations, brings up fake api), but the other services are skipped after doing a GET to check the database flags.
