### ISSUE TITLE
UI enhancements to make it more user-friendly and professional

### ISSUE THREAD

**Issue by mohit5it9** [Shippable/admiral#1548]
https://github.com/Shippable/pm/issues/9817

- [ ] Remove the background color for close button for modal
- [ ] On selecting label for a radio button, the button should be set/unset
- [ ] Adds EULA Agreement to the right-hand side panel
- [ ] Adds popup error msg like in our APP UI

**Comment by ric03uec** [comment]
@mohit5it9 
- EULA should be on the left nav bar

**Comment by ric03uec** [comment]
closing, add all these in scenario issues
