### ISSUE TITLE
9817.8 user should be able to see database configuration and logs in modals

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1555]
- https://github.com/Shippable/pm/issues/9817
- show the database address and port in the database section. the db section right now says `A short one liner on what this section is...`. it should be replaced with two read-only fields that show database address and port
- the config modal will show all the fields that are being shown on the old UI
- theres a bug in the modal where its not wrapping the text fields,

**Comment by mohit5it9** [comment]
#### MOCKUPS
for a large IP Addresses:
![image](https://user-images.githubusercontent.com/11424742/34820137-b2ab54d2-f6e5-11e7-995f-1c77c2447f50.png)

when database is not initialized:
![image](https://user-images.githubusercontent.com/11424742/34820364-53e595ce-f6e6-11e7-9ff8-448bc973888e.png)

when db is up and running:
![image](https://user-images.githubusercontent.com/11424742/34820393-6cd4ca82-f6e6-11e7-8669-ee4ea7360152.png)

**Comment by ric03uec** [comment]
looks good

**Comment by mohit5it9** [comment]
this is done
![image](https://user-images.githubusercontent.com/11424742/34823909-54e94d06-f6f2-11e7-9936-7db665f47a2c.png)

fixed the modal config bug also
![image](https://user-images.githubusercontent.com/11424742/34823928-61a1baa6-f6f2-11e7-8a6a-2a61879a2ef8.png)
