### ISSUE TITLE
9817.9  user should be able to initialize vault as onebox from the new UI

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1558]
- https://github.com/Shippable/pm/issues/9817
- show the three options for node init in dropdown (This Node, New Node, Existing) if the vault is not initailized
- if vault is initialized, the dropdown should show the option using which it was initialized as read-only
   - the dropdown should be disabled
- show the vault server ip address after the dropdown
- the `config` modal should show all the fields that are shown on the old UI

**Comment by priyakirankumar** [comment]
This is for the Secrets section.

**Comment by ric03uec** [comment]
- can we remove the `New node details are updated` string. not sure if thats required

**Comment by priyakirankumar** [comment]
Missed disabling the Save button (on modal) if all fields are not updated. Will do this.

**Comment by priyakirankumar** [comment]
Since Admiral on RC has been 'Initialized', I was not able to test the Secret's modal/popup to add new/existing nodes.
I have tested the changes on my sandbox's onebox.
