### ISSUE TITLE
9817.10 user should be able to initailize vault on a new node from the new UI

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1578]
- https://github.com/Shippable/pm/issues/9817
- user should be able to initailize vault on a new node from the new UI

**Comment by priyakirankumar** [comment]
As per @ric03uec :
- save the values for new vault server initialization on a different host
- show the vaules for vault if it has been already initailized on a different host
- make sure all user  workflows on new UI are consistent with old UI

**Comment by ric03uec** [comment]
@deepikasl theres a UX issue on the panel
- go to secrets section
- click on dropdown and select new node
- dont add any settings and close the modal
- click on the dropdown and select this node
- at this point, the button for `add new/existing node details` should NOT show. it is showing right now and is quite misleading. we should fix it here only

**Comment by deepikasl** [comment]
ok,
Also, When adding new node by giving Ip address, and initializing it. Console error: `initType of undefined` is seen.

**Comment by ric03uec** [comment]
this is working as expected, closing
