### ISSUE TITLE
9817.13 user should be able to initialize rabbitmq on a new node using new UI

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1581]
- https://github.com/Shippable/pm/issues/9817

**Comment by mohit5it9** [comment]
un-assigning in favor of https://github.com/Shippable/admiral/issues/1593

**Comment by deepikasl** [comment]
This is complete.
![screenshot from 2018-01-15 10 50 52](https://user-images.githubusercontent.com/18304961/34928198-fa11ef80-f9e1-11e7-99e7-6c21ffe4b1e3.png)
