### ISSUE TITLE
9817.14  user should be able to configure existing rabbitmq server from the new UI

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1582]
- https://github.com/Shippable/pm/issues/9817

**Comment by deepikasl** [comment]
This is complete.
![screenshot from 2018-01-15 10 54 04](https://user-images.githubusercontent.com/18304961/34928297-95275e9c-f9e2-11e7-92bd-f26a4a47c2e3.png)
![screenshot from 2018-01-15 10 54 15](https://user-images.githubusercontent.com/18304961/34928302-a0b57500-f9e2-11e7-81c4-284df3102f5b.png)
