### ISSUE TITLE
[bug] clicking on the entire bar should show/hide section

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1592]
- https://github.com/Shippable/pm/issues/9817
- for any section, clicking on the entire bar should toggle show/hide, not just the -/+ button. this will make it consistent with the behavior of Shippable ui
![image](https://user-images.githubusercontent.com/1110988/34871128-70622290-f7b2-11e7-82fe-6b73e0c1fef4.png)

**Comment by priyakirankumar** [comment]
- Remove "portlet-heading" inline style while doing these changes.

**Comment by priyakirankumar** [comment]
Verified on RC.
