### ISSUE TITLE
9817.17 user should be able to configure existing gitlab server from the new UI

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1595]
- https://github.com/Shippable/pm/issues/9817

**Comment by mohit5it9** [comment]
this is done.
verified locally.
checked the logs, there were no errors and the initialization succeeded

**Comment by mohit5it9** [comment]
missed adding validation checks for existing nodes
reopening to add this

**Comment by mohit5it9** [comment]
verified verification logic locally
