### ISSUE TITLE
9817.18  user should be able to configure redis as onebox from new UI

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1596]
- https://github.com/Shippable/pm/issues/9817

**Comment by priyakirankumar** [comment]
Verified details on RC. Verified the functionality on local onebox, as RC was 'Initialized'.

![image](https://user-images.githubusercontent.com/16892929/34929848-42062f2c-f9ec-11e7-9e3e-f762a0f68b4e.png)
