### ISSUE TITLE
9817.21 user should be able to configure new swarm cluster from new UI

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1599]
- https://github.com/Shippable/pm/issues/9817

**Comment by priyakirankumar** [comment]
![image](https://user-images.githubusercontent.com/16892929/34938981-3a1667a4-fa10-11e7-9150-fa0e01d51e11.png)

![image](https://user-images.githubusercontent.com/16892929/34938996-455d607c-fa10-11e7-9ef6-02ce959aef7d.png)

**Comment by ric03uec** [comment]
looks good

**Comment by priyakirankumar** [comment]
Verified the details showing up on RC.

![image](https://user-images.githubusercontent.com/16892929/34940116-5b853ace-fa14-11e7-8e3a-78ac8591cec2.png)

![image](https://user-images.githubusercontent.com/16892929/34941314-3c61c446-fa19-11e7-9f8c-372e8ede08eb.png)
