### ISSUE TITLE
remove node selection option from modal

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1607]
- https://github.com/Shippable/pm/issues/9817
- we're providing an option to the user for selecting the type of node they want to install the component on from the dropdown
- there's no point in repeating this selection after the modal pops up too
- we should remove the new node/existing node selection from them modal
- the only option available in the modal should be the option user has already selected from the dropdown

**Comment by priyakirankumar** [comment]
- Hide the `add new/existing node details` if it is disabled.

**Comment by priyakirankumar** [comment]
Verified modal in sandbox. Show selected option on the Modal.
![image](https://user-images.githubusercontent.com/16892929/34974537-9cd2243e-fab3-11e7-820b-a1f99abed0d5.png)


Verified in RC. Button is hidden when button is disabled.
![image](https://user-images.githubusercontent.com/16892929/34974248-0d3d5d30-fab2-11e7-8b9a-425a62e12031.png)
