### ISSUE TITLE
9817.22 user should be able to configure API settings

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1619]
- https://github.com/Shippable/pm/issues/9817
- add a new tab for `Config and Install` section on the left navbar
- user should be able to configure API (external, internal and console) settings from the new UI

**Comment by priyakirankumar** [comment]
Add the new look-n-feel to the display

![image](https://user-images.githubusercontent.com/16892929/34972336-e637bb96-faa6-11e7-9a7e-ebf91a840bce.png)

**Comment by mohit5it9** [comment]
verified on rc
![image](https://user-images.githubusercontent.com/11424742/35029868-e3587014-fb82-11e7-8730-d247e63ec833.png)

**Comment by ric03uec** [comment]
@mohit5it9 this is not complete
- the summary section needs to be removed. its not required here
- this entire panel should only show up if the first panel is initialized correctly.

**Comment by mohit5it9** [comment]
this is done now

**Comment by mohit5it9** [comment]
re-opening to add some minor UI enhancements

**Comment by ric03uec** [comment]
@mohit5it9 is this complete?

**Comment by mohit5it9** [comment]
This is done
Closing
