### ISSUE TITLE
9817.23 user should be able to configure gitlab settings from new UI

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1620]
- https://github.com/Shippable/pm/issues/9817
- user should be able to configure gitlab settings from new UI

**Comment by priyakirankumar** [comment]
Add the new look-n-feel to the display

![image](https://user-images.githubusercontent.com/16892929/34972395-47af325a-faa7-11e7-9126-95f40e537150.png)

**Comment by mohit5it9** [comment]
verified on rc
