### ISSUE TITLE
9817.29 user should be able to configure build node settings from the new UI

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1627]
- https://github.com/Shippable/pm/issues/9817
- user should be able to configure build node settings from the new UI

**Comment by priyakirankumar** [comment]
![image](https://user-images.githubusercontent.com/16892929/34972440-89636aea-faa7-11e7-81ed-7eaeb3e79604.png)

**Comment by mohit5it9** [comment]
verififed on rc
