### ISSUE TITLE
9817.36 user should be able to configure misc system level configuration

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1634]
- https://github.com/Shippable/pm/issues/9817
- add a new tab on the left navbar for configuring system settings
- user should be able to configure misc system level configuration from the system settings section in new UI

**Comment by priyakirankumar** [comment]
![image](https://user-images.githubusercontent.com/16892929/35025416-6ef70120-fb6b-11e7-802f-d486f57f006d.png)

**Comment by ric03uec** [comment]
@priyakirankumar the following also needs to move to system settings
- ignore TLS Errors (from configure and install section)
- IRC checkbox (from configure and install section)
- email provider (from configure and install section)

**Comment by priyakirankumar** [comment]
Verified on local sandbox.

**Comment by priyakirankumar** [comment]
As per @ric03uec, we should show this section only if `infrastructure` AND `config and install` have been run successfully

**Comment by priyakirankumar** [comment]
Verified on local sandbox.
