### ISSUE TITLE
9817.5 user should be able to see the list of servers in summary section

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1638]
- https://github.com/Shippable/pm/issues/9817
- user should be able to see the list of servers in summary section
- show a table like following

|Nodes| Admiral | Database | Secrets | Messaging | State | Redis | Swarm Master | Swarm Workers |
|---|---|---|---|---|---|---|---|---|
|1.1.1.1| x | | | | | | | |
|1.1.1.2|  |x|x| |x| | | |

- a cross should be shown in front of any component if and only it has `isInitialized` and `isInstalled`=true

**Comment by ric03uec** [comment]
@amalfra eod status on this?
can we make sure that issues are getting updated with status.

**Comment by amalfra** [comment]
ok, will do. The pr was opened yesterday night but was submitted for review today only.

**Comment by amalfra** [comment]
rc verified
