### ISSUE TITLE
add eula button in settings panel

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1676]
- https://github.com/Shippable/pm/issues/9817
- remove the settings button from top right corner
- add links to docs, support and EULA
- this should look similar to the main product top right panel
![image](https://user-images.githubusercontent.com/1110988/35095796-dc19ac6c-fc6f-11e7-80c0-ff65dbc78b04.png)

**Comment by ric03uec** [comment]
use the font awesome icon for `legal` for eula

**Comment by amalfra** [comment]
rc verified
