### ISSUE TITLE
[bug] logout button not correctly aligned

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1679]
- https://github.com/Shippable/pm/issues/9817
- when the left navbar is collapsed, the logout button is not aligned correctly
![image](https://user-images.githubusercontent.com/1110988/35095169-88085a3a-fc6d-11e7-9d59-6e8802cc3bba.png)

**Comment by ric03uec** [comment]
also, when navbar is collapsed, the arrow should point out
![image](https://user-images.githubusercontent.com/1110988/35095727-8fa2a550-fc6f-11e7-9dd2-cca72428b383.png)

**Comment by deepikasl** [comment]
Verified on rc.
