### ISSUE TITLE
fix messages on the panels

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1704]
- https://github.com/Shippable/pm/issues/9817
- on the `configure and install` panel, when the infra is not initialized, show the message `Please initialize Infrastructure before starting configuration`
- on the addons panel, when infra/config is not initailized, show the mesage `Please configure the installation before installing addons`
- on the system settings panel, when infra/config is not initailized, show the message `Please configure the installation before changing system settings`

**Comment by ric03uec** [comment]
- Upload artifacts to AWS should be renamed to `Enable build artifact caching using AWS S3.`

**Comment by deepikasl** [comment]
Couldn't verify the messages on rc. As its already initialized. Verified this locally.
