### ISSUE TITLE
change the default cluster type

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1705]
- https://github.com/Shippable/pm/issues/9817
- Default cluster type should be custom Ubuntu 16.04 (and not dynamic). I don't think server customers are going to use dynamic nodes.

<img width="803" alt="screen shot 2018-01-18 at 4 16 21 pm" src="https://user-images.githubusercontent.com/26096758/35128366-16d56b02-fc6b-11e7-8ee2-46caac9f0d8c.png">

**Comment by deepikasl** [comment]
Verified locally, by configuring admiral and initializing DB.
![screenshot from 2018-01-22 13 49 29](https://user-images.githubusercontent.com/18304961/35211133-297f8676-ff7b-11e7-96d8-8f686c8afb34.png)
Couldn't verify on rc as DB is already initialized.
