### ISSUE TITLE
[bug] rendering issues

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1706]
- https://github.com/Shippable/pm/issues/9817
- If the browser is not full screen (for mac book), the left panel is completely hidden.

<img width="239" alt="screen shot 2018-01-18 at 11 46 43 am" src="https://user-images.githubusercontent.com/26096758/35119885-3676cd40-fc4b-11e7-908a-6eb42e1a889f.png">

- if browser is not full screen (firefox), the top bar overflows into the left panel and renders it unusable

![image](https://user-images.githubusercontent.com/1110988/35206716-a6562efa-ff64-11e7-96bc-d38f9f3e641c.png)

**Comment by priyakirankumar** [comment]
Verified on RC.
![image](https://user-images.githubusercontent.com/16892929/35209725-5d86b562-ff75-11e7-9989-80b58359246b.png)
