### ISSUE TITLE
[bug] issues in infrastructure initialize workflow

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1707]
- https://github.com/Shippable/pm/issues/9817
- If you do keep clicking on Initialize button in the disabled state, it disappears. Overall, the disabled state of the button is poorly indicated visually. I did not have a clue that the button was disabled because some checkboxes were not clicked (that need to be clicked after the SSH auth script is run) for some component. We should clearly indicate why the button is disabled with a call to action, since in the new UI the initialization is hidden in a panel and not visible. 

<img width="1168" alt="screen shot 2018-01-18 at 12 01 51 pm" src="https://user-images.githubusercontent.com/26096758/35119273-4aed5f02-fc49-11e7-8858-366821a509da.png">
- show status code colors for initializing, failed, initialized steps
    - use the same status code colors that are being used for Shippable
    - show those code when the component is in processing, success or failed etc
- disable the Initialize button when any component is in initializing phase.
- all action buttons on the infra panel should be disabled when any component is being initialized

**Comment by amalfra** [comment]
rc verified
