### ISSUE TITLE
verify that ip address validation is working for all fields

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1709]
- https://github.com/Shippable/pm/issues/9817

**Comment by deepikasl** [comment]
Verified for:
- [ ] 1. API Url
- [ ] 2. Internal API Url
- [ ] 3. Console API url
- [ ] 4. State url
- [ ] 5. amqp url
- [ ] 6. amqp root url
- [ ] 7. amqp admin url
- [ ] 8. Redis url
- [ ] 9. BBS url
- [ ] 10. GHE url
- [ ] 11. Gitlab url
- [ ] 12. Shippable UI url
