### ISSUE TITLE
[bug]  sometimes while initializing we are getting console errors and the install stops

### ISSUE THREAD

**Issue by mohit5it9** [Shippable/admiral#1725]
https://github.com/Shippable/pm/issues/9817

**this is happening randomly. not all times**

![image](https://user-images.githubusercontent.com/11424742/35259925-84a25bb0-002e-11e8-95a9-543cd7380b2d.png)

![image](https://user-images.githubusercontent.com/11424742/35259949-a9949e2e-002e-11e8-854e-123d07b8e5a0.png)

**Comment by amalfra** [comment]
verified locally with fresh install on one node as well as two nodes
