### ISSUE TITLE
add login2 page which loads the new admiral login ui

### ISSUE THREAD

**Issue by Bharath92** [Shippable/admiral#1736]
https://github.com/Shippable/pm/issues/9817

**Comment by mohit5it9** [comment]
Eod: was able to figure out why the login2 page is not coming. Have a solution that is working on local..will need further testing and will send the pr after release.

**Comment by mohit5it9** [comment]
verified on rc, the login behaviour
this is the default behavior for now:

- if a user is logged out and he tries to go to the dashboard or dashboard2 page, then by default he'll be going to the old login page.

- if a user is on the login2 page and then he logins, he is taken to the new dashboard and on logout from there he is taken to the new login page
