### ISSUE TITLE
[bug] old password shown after password re-enter for state during initialization

### ISSUE THREAD

**Issue by Bharath92** [Shippable/admiral#1737]
https://github.com/Shippable/pm/issues/9817
give a wrong password for state.
click initialize. state initialize fails
give a correct password.
initialize

this will show the wrong password during initialization process

**Comment by amalfra** [comment]
EOD: figured out and fixed fields getting reset to old values after initialization process. Still trying to figure out why during initialization process it's getting reset. Will raise pr after fixing that too

**Comment by amalfra** [comment]
verified using one and two box installs
