### ISSUE TITLE
[usability bug] Shippable UI section should be above configuring auth & scm provider sections

### ISSUE THREAD

**Issue by Bharath92** [Shippable/admiral#1739]
https://github.com/Shippable/pm/issues/9817

`Shippable UI` section is below `AUTHORIZATION AND SOURCE CONTROL MANAGEMENT (SCM) PROVIDERS` section. This is counter-intuitive to the users because whatever values are present in the `Shippable UI` section shows up in `AUTHORIZATION AND SOURCE CONTROL MANAGEMENT (SCM) PROVIDERS`section

**Comment by ric03uec** [comment]
@Bharath92 lets open this in a separate issue since this was not in the scope of current task
