### ISSUE TITLE
8312 - gitlab password length

### ISSUE THREAD

**Issue by trriplejay** [Shippable/admiral#192]
Shippable/pm#8312

gitlab requires minimum length 8 password.
we should check it in the state POST route

we also might want to consider checking directly in the UI so that the intialization doesnt get partway through before failing due to password length.

we could also check in initailize/checkInputParams, but it seems like we should minimize the number of places we have to do this check.

**Comment by stephanielingwood** [comment]
we'll deal with this later. deferring.
