### ISSUE TITLE
8312 - polling for initialize status

### ISSUE THREAD

**Issue by trriplejay** [Shippable/admiral#193]
Shippable/pm#8312

now that we are performing many long steps in the initialize workflow, we are running into timeout type issues when installing from a brand new box.  We should switch things up here.

- POST `/workflow/initialize` should return a response immediately if checkInputParams passes
- the async series should continue after the response is sent (like how triggerNewBuildRequest responds to github before continuing to process)
- we should add a new field to each systemConfigs field (db, msg, state, secrets, redis, msg) that represents whether or not the item is in the middle of initializing. something like `isProcessing`
- for each POST route for each item, we should start the route (after checkInputParams) by setting the new flag to TRUE, and each route should end by setting the flag back to FALSE.  Make sure that the flag is set to false in the event of any error in the POST workflow.
- in the UI, after the initialize call returns successfully, we should begin polling the systemConfigs every couple seconds.  as long as one of the items is set to 'isProcessing=true`, we should disable the 'initialize' button.
- once all items come back with 'isProcessing=false', we should re-enable the button. once all items say 'isInitialized=true` then we can stop polling.

**Comment by trriplejay** [comment]
I'm thinking this instead:

2 new flags for each components sytemConfigs section:
isProcessing
isFailed

at the beginning of each POST route, isProcessing should be set to true and isFailed to false
at the end of each POST route, if no error, set isProcessing to false, and set isFailed to false
at the end of each POST route, if there was an error, set isFailed to true and isProcessing to false

add a helper script in common called 'putComponentStatus.js'.  This should allow anyone to update the systemconfigs.`component` section without overwriting existing fields not present in the update object. should be a function that takes in (component, update),where update is an object like `{isProcessing: true, isInitialized: true}`.  route should first read the system configs, safely json parse the existing component settings, then extend the existing settings with the `update` object passed in, then return the updated object. in the callback (err, object)

in the UI, we can show in the table which component has an isFailed status, to indicate that the logs should be examined.

UI can poll systemConfigs every couple seconds when initialize button is clicked. stop polling and re-enable the button either when all components have isInitialized=true, OR when any component has isFailed=true

**Comment by stephanielingwood** [comment]
complete. closing.
