### ISSUE TITLE
8312 Error after logging in 

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#198]
- https://github.com/Shippable/pm/issues/8312
- getting the following error immediately after logging in the ui
![image](https://cloud.githubusercontent.com/assets/1110988/25026772/15acada2-205d-11e7-82bb-8f0ee35fab4e.png)
- the token is valid since the login succeeds. the network tab suggests that GET /api/systemConfigs call does not set any token on the request

**Comment by stephanielingwood** [comment]
complete. closing.
