### ISSUE TITLE
8344.1 Update POST /api/systemIntegrations

### ISSUE THREAD

**Issue by a-murphy** [Shippable/admiral#222]
Shippable/pm#8344

Update the `POST /api/systemIntegrations` route to:
  * call `PUT /api/masterIntegrations` to enable the master integration
  * call `GET /api/masterIntegrationFields` to get the fields for the appropriate master integration
  * check that the fields in the `POST` body are the correct master integration fields
  * save the integration values in the database and in vault

**Comment by stephanielingwood** [comment]
complete. closing.
