### ISSUE TITLE
8344.2 Display system integrations

### ISSUE THREAD

**Issue by a-murphy** [Shippable/admiral#228]
Shippable/pm#8344

Get the list of system integrations from `GET /api/systemIntegrations` and show these integrations in the install panel.  Each integration will have a hard-coded section in the HTML and use the response from `GET /api/systemIntegrations` to display the correct values.

![install panel](https://cloud.githubusercontent.com/assets/1110988/25059484/628e8002-213c-11e7-9611-4d0e9df0461b.png)

**Comment by stephanielingwood** [comment]
complete. closing.
