### ISSUE TITLE
8344.2 Add PUT /api/systemIntegrations/:systemIntegrationId

### ISSUE THREAD

**Issue by a-murphy** [Shippable/admiral#229]
Shippable/pm#8344

Add a `PUT /api/systemIntegrations/:systemIntegrationId` route and update the UI to call this route to update existing integrations.
  * User should be able to edit any system integration using the UI
  * When the install button is clicked, the `PUT` route is called to update the updated integrations

**Comment by stephanielingwood** [comment]
complete. closing.
