### ISSUE TITLE
8344.4 Start Nexec

### ISSUE THREAD

**Issue by a-murphy** [Shippable/admiral#236]
Shippable/pm#8344

After starting Sync (on clicking "install"), start Nexec. Give it the following environment variables:
  * SHIPPABLE_API_URL
  * SHIPPABLE_API_TOKEN
  * SHIPPABLE_API_RETRY_INTERVAL
  * CONSOLE_BUFFER_LENGTH

**Comment by stephanielingwood** [comment]
using the variables currently passed to nexec by base on boot:

- SHIPPABLE_API_TOKEN
- SHIPPABLE_API_URL
- SHIPPABLE_ROOT_AMQP_URL
- SHIPPABLE_AMQP_DEFAULT_EXCHANGE

**Comment by stephanielingwood** [comment]
complete. closing.
