### ISSUE TITLE
8344.3 Add GET /api/services

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#264]
- Shippable/pm#8344

- Add `GET /api/services?name=<foo>`:
    - accepts query param to return the service with name
    - if no query param specified, return all services
    - if no services pesent in DB, then parse `services/services.json` file to create services array in system settings for core services
    - the format for `services` object in `systemSettings` is
```
{
    "api": { "serviceName": "api", "mounts": "", "envs": "", "opts": "", "replicas": "global"},
    "www": { "serviceName": "www", "mounts": "", "envs": "", "opts": "", "replicas": "global"},
    "mktg": { "serviceName": "mktg", "mounts": "", "envs": "", "opts": "", "replicas": "global"},
    "sync": { "serviceName": "sync", "mounts": "", "envs": "", "opts": "", "replicas": 1}
}
```

**Comment by stephanielingwood** [comment]
complete. closing.
