### ISSUE TITLE
8344 all inputs disappear after refreshing ui

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#285]
- https://github.com/Shippable/pm/issues/8344
- steps to repro
    - log in to the ui
    - run initialize
    - once initialize is complete, click `Install` section
    - refresh the page
    - page doesnt show any content
![image](https://cloud.githubusercontent.com/assets/1110988/25251428/2e4b53c4-25ce-11e7-9898-eebc99f9793c.png)

- note that the url also changes after refresh. Before refresh the url is `localhost:50003/#installPanel` and after refresh its `localhost:50003/installPanel`

**Comment by a-murphy** [comment]
Anything other than `/login` will now redirect to the dashboard.
