### ISSUE TITLE
8344.3 fix github system integration 

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#286]
- https://github.com/Shippable/pm/issues/8344
- update github auth system integration to show following values in UI
    - Client Id (textbox, editable)
    - Client secret (textbox, editable)
    - WWW Url (textbox, non editable. Value is set from www system integration )
- verify that client id and client secret values are correctly being set in vault
- move the section to edit system configuration before auth provider section

**Comment by stephanielingwood** [comment]
complete. closing.
