### ISSUE TITLE
8344 UI gets stuck when configuring settings and services

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#288]
- https://github.com/Shippable/pm/issues/8344
- to repro
    - run admiral from scratch
    - configure gitlab/rabbitmq/accesskey/secret key and hit initialize
    - once initialization is complete. click `Install` to open install panel
    - hit `Install`. The button now stays disabled. logs show that response was returned from backend
![image](https://cloud.githubusercontent.com/assets/1110988/25253769/24c77cf2-25d7-11e7-85db-5ca9f5ca64cd.png)
   - no services are started

**Comment by stephanielingwood** [comment]
this doesn't appear to be happening anymore. closing. will reopen if needed.
