### ISSUE TITLE
8344 Show provider login buttons on www login page

### ISSUE THREAD

**Issue by stephanielingwood** [Shippable/admiral#290]
https://github.com/Shippable/pm/issues/8344

Not sure why they're not being shown right now.
![login](https://cloud.githubusercontent.com/assets/7757711/25255044/b29c1b18-25dd-11e7-99c0-9259aa910e5c.png)

**Comment by ric03uec** [comment]
its based on url in the system integration. if the wwwUrl in github system integration is `127.0.0.1`, then use that in address bar instead of `localhost`

**Comment by stephanielingwood** [comment]
not needed. closing.
