### ISSUE TITLE
8344 fix gitlab system integration

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#293]
- https://github.com/Shippable/pm/issues/8344
- gitlab system integration currently stores `username`, `url`, `providerId`, `password`
- the correct fields to be stored are `username`, `url`, `sshPort`, `subscriptionProjectLimit`, `username` and `providerId`
- sync fails to create gitlab projects because of incorrect values and throws following error in logs
![image](https://cloud.githubusercontent.com/assets/1110988/25256988/abe9b364-25e9-11e7-85df-4e050775b4e3.png)

**Comment by stephanielingwood** [comment]
complete. closing.
