### ISSUE TITLE
8344 Installer secret key text box is not removed after intialization

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#298]
- https://github.com/Shippable/pm/issues/8344
- to reproduce
    - run latest installer
    - set values for access key, secret key, gitlab and rabbitmq
    - hit initialize
    - once initialization is completed successfully, the secret key text box is not removed.
![image](https://cloud.githubusercontent.com/assets/1110988/25289907/71afcfac-2680-11e7-8448-4273b6d357a9.png)

- refreshing the page removes it

**Comment by stephanielingwood** [comment]
complete. closing.
