### ISSUE TITLE
8184.6 DEV initialize database

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#3]
- https://github.com/Shippable/pm/issues/8184
- when app boots up, initialize database container and set correct mounts
- run the script to bootstrap database with systemConfigs table and insert default values in it

**Comment by stephanielingwood** [comment]
1. **db installation**
    - set data mount from `/var/run/shippable/db/ship:/ship` in the container
    - set data mount from `/etc/shippable/db/:/etc/shippable/db` in the container for postgres config file
    - PGDATA env should be `/ship` 
    - POSTGRES_USER env is `$DB_USER`
    - POSTGRES_PASSWORD env is value of `$DB_PASSWORD`
    - POSTGRES_DB env is `shipdb`
    - make sure port 5432 on container is mapped to 5432 on host
