### ISSUE TITLE
8385 Use text box for bitbucket secret key field

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#399]
- https://github.com/Shippable/pm/issues/8385
- the `Client Secret` input for bitbucket server should be a text box. This is because the private key used here will have newlines that need to be formatted correctly. This should be exactly the same as pem key account integration

![image](https://cloud.githubusercontent.com/assets/1110988/25448000/fec94dac-2a6b-11e7-8061-37d427ee2d19.png)

- also make sure that the value saved in backend is escaping newlines

**Comment by stephanielingwood** [comment]
complete. keys are now being added with correct new lines. closing.
