### ISSUE TITLE
8385 Disabling dyamic nodes is not removing ec2 and marshaller

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#407]
- https://github.com/Shippable/pm/issues/8385
- when dynamic nodes integration is disabled from admin panel, ec2 and marshaller services should be removed 
- marshaller is also not started when the `services` column is reset in the db and user clicks `Install` from admin panel

**Comment by stephanielingwood** [comment]
two changes:
- In DELETE /api/systemIntegrations, disable the masterIntegration only if there are no other systemIntegrations using that master integration
- Remove logup from core services; it should be started when the amazonKeys masterInt is enabled
- In the addons panel, call a PUT on every masterintegration when the addons button is clicked. (Right now the masterIntegration PUT is only being called when it has changed.)

**Comment by stephanielingwood** [comment]
complete. closing.
