### ISSUE TITLE
8405 error initializing system node

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#434]
- https://github.com/Shippable/pm/issues/8405
- super users cannot initialize a system node. adding a new node and clicking `Initialize` throws following error

![image](https://cloud.githubusercontent.com/assets/1110988/25568492/d27c402e-2db8-11e7-8bb2-8bddf29a4c38.png)

**Comment by a-murphy** [comment]
This should be an issue in API.  It's not looking for the system integration.

**Comment by ric03uec** [comment]
closing this. added a new issue in api
