### ISSUE TITLE
8413 Do not write any secrets in systemSettings

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#538]
- https://github.com/Shippable/pm/issues/8413
- remove all passwords, keys, usernames, tokens from `systemSettings` table
- these should either be stored in `systemIntegrations` or `admiral.env`.

**Comment by stephanielingwood** [comment]
also need to update the base migate.js file to remove these fields as well.

**Comment by a-murphy** [comment]
Usernames and passwords have been removed from the config columns in systemSettings.
