### ISSUE TITLE
8413 show empty configs when db not initialized

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#557]
- https://github.com/Shippable/pm/issues/8413
- when `Config` button is clicked for any service before the DB is initialized, the user gets following error
![image](https://cloud.githubusercontent.com/assets/1110988/25817955/db85e8b6-33dd-11e7-8966-37d085ba9b52.png)
- instead of an error, the route should return empty object and configs modal should show no rows.

**Comment by stephanielingwood** [comment]
Decided to disable the configs buttons instead, as this is behavior we should change in the UI, instead of the api. 

complete. closing.
