### ISSUE TITLE
8184.10 DEV Add db info and system configs to database tab

### ISSUE THREAD

**Issue by stephanielingwood** [Shippable/admiral#57]
https://github.com/Shippable/pm/issues/8184

Drawing from the heap issue (https://github.com/Shippable/heap/issues/659):
![image](https://cloud.githubusercontent.com/assets/7757711/24466355/707073c6-1465-11e7-9e70-ddea4f3c5d73.png)

**Comment by a-murphy** [comment]
Tested on a new Digital Ocean droplet.
