### ISSUE TITLE
8413.15 add section to show super users in UI

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#589]
- https://github.com/Shippable/pm/issues/8413
- add a section in addons titled `System super users`
- this should show an empty text box followed by a list of accounts that are returned by `GET /api/superusers` route
- when user clicks `Install`, the value in text box is POST-ed in `/api/superusers` route if it is non-empty
- if its empty, skip the post
- all items in the list should have a `x` mark after the id
- clicking it should mark the account id for deletion from account roles table
- when user clicks `Install`, all the accounts which have been marked for deletion should be removed from account roles table

**Comment by stephanielingwood** [comment]
complete. closing.
