### ISSUE TITLE
8413 usability fixes

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#591]
- https://github.com/Shippable/pm/issues/8413
- once admiral cli is complete, the user prompt should show `Go to <ip address> to access admin panel` instead of `Go go <ip address> to access admiral`
- for the rabbitmq password box, add a placeholder that says `must be 8 characters or more`
- for the gitlab password box, add a placeholder that says `must be 8 characters or more`
- add a new cli command called info i.e. `./admiral.sh info`. thsi should print
    - release version
    - admiral ui ip address
    - login token
    - db address
- remove `ssh-key` addon from the list. this should always be enabled because its required by system integrations. hence users should not even see the option of disabling it
- remove all `console.log` statements from `child_process` calls in api
    - the output from `stdout` should be logged as logger.debug
    - the output from `stderr` should be logged as logger.error

**Comment by a-murphy** [comment]
Tasks have been created for all of the points listed above.  (See the preceding linked issues.)

**Comment by stephanielingwood** [comment]
all sub-tasks are complete. closing.
