### ISSUE TITLE
[bug] Cannot bring up new machines in RC

### ISSUE THREAD

**Issue by shrivara** [Shippable/admiral#683]
We tried to bring up new machines in RC today. We ran the following steps:
1. Remove `machines1`.
2. Remove `machines2`.
3. Add `machines3` with new IP.
4. Add `machines4` with new IP.
5. Run the command to add SSH keys on the `machines3`, `machines4`(after running `sudo su`).
6. Run initialise. 

We ran into the following problems:
* First, `secrets` machine was not initialising because port was a string "8200" and it would fail [this](https://github.com/Shippable/admiral/blob/master/api/state/initialize.js#L106) validation. We couldn't find a way to update this in the UI. So, we updated this to a number in DB.
* We found a few more ports stored as strings(although we didn't check if these had `isNumber` validations) and we fixed them all.
* After we fixed this, `secrets` would still fail to initialize as it attempted to unseal an already sealed Vault. There are a few issues in the initialize call. Its not making the [right call](https://github.com/Shippable/admiral/blob/master/api/secrets/initialize.js#L354)(doesn't return `isSealed` in response) to obtain sealed status. The [condition to check if unseal](https://github.com/Shippable/admiral/blob/master/api/secrets/initialize.js#L474) is required is wrong.

We didn't proceed beyond this and attempted to bring up the machines using base instead to unblock everyone.

**Update:** Bringing up new machines using base also failed as a few required envs aren't set from base. Didn't realize that admiral has completely different flow. Since, we didn't want to break existing `systemSettings` by removing it, we left it as it is. This is the [PR](https://github.com/Shippable/infra/commit/e8047fa626e3feb22ddfcac00c70270f8a0f85ab) used to bring up new machines. If admiral will have problems with base initialised machines, new machines can be brought up similarly. 

https://github.com/Shippable/pm/issues/8413

**Comment by ric03uec** [comment]
this is now working in RC, closing
