### ISSUE TITLE
8184.9 DEV add login page

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#7]
- https://github.com/Shippable/pm/issues/8184
- once admiral boots up, it should show a login page with a field to enter login token
- mockup of this is available in heap

**Comment by a-murphy** [comment]
I've started adding Angular and will continue with this tomorrow.  Hopefully the login page will be working (with logging in continuing to another page) sometime tomorrow.

**Comment by a-murphy** [comment]
Still working on this because I switched to the jobs routes documentation tomorrow.  Angular is now installed and I'm working on the last of the most important dependencies.

**Comment by a-murphy** [comment]
Partially complete.  The login page loads, saves a cookie, and isn't the only page.  I still have to work on checking that the token entered is valid.  (There's an API route for it now.)

**Comment by stephanielingwood** [comment]
1. The admin login page should just ask for token. Details in `Mockup` section of https://github.com/Shippable/heap/issues/659

**Comment by a-murphy** [comment]
Appears to be working.
