### ISSUE TITLE
8512 make keys optional  in UI initialize workflow

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#761]
- https://github.com/Shippable/pm/issues/8512

**Comment by ric03uec** [comment]
@a-murphy can you look at this. we should remove the red-borders around the key text boxes if the key is not provided by the user

**Comment by ric03uec** [comment]
- we should also change the help text to say `Access Key (Optional)` and `Secret Key (Optional)`

**Comment by a-murphy** [comment]
Anything else to be done here?

**Comment by ric03uec** [comment]
nothing else required here.
