### ISSUE TITLE
8184.10 DEV show dashboard page

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#8]
- https://github.com/Shippable/pm/issues/8184
- once the login is complete, show the page that lists all system configs
- mockup if this is available in corresponding heap issue
- https://github.com/Shippable/admiral/issues/9 should be completed before showing this page

**Comment by a-murphy** [comment]
Update from Devashish:
- add dashboard view. Should be an angular app
     - dashboard loads post login and calls GET /systemConfigs route to get system configs
     - it shows the database config from the env variables

**Comment by stephanielingwood** [comment]
1. Front page on admin UI should show db information and system configs. Details in `Mockup` section of https://github.com/Shippable/heap/issues/659
