### ISSUE TITLE
8312.2 UI - Create the initialize panel

### ISSUE THREAD

**Issue by stephanielingwood** [Shippable/admiral#82]
Shippable/pm#8312

  - Refer to diagrams
  - When the user clicks "initialize", call POST `api/db/initialize`, then show the table view. Only the database should be in the table view.
  - Poll GET /api/systemConfigs; when systemConfig.database has initialized: true, show the db status as initialized
  - Also add Install and Add Ons panels - they are disabled for now

![installer-initialization-mvp2](https://cloud.githubusercontent.com/assets/7757711/24812998/357b6bae-1b81-11e7-8f4a-d486d36de426.png)

![installer-mvp2-initcomplete](https://cloud.githubusercontent.com/assets/7757711/24813007/3f436f9c-1b81-11e7-85a3-50c67d9b0034.png)

**Comment by trriplejay** [comment]
complete.
