### ISSUE TITLE
8312.3 Add POST /api/workflow/initialize

### ISSUE THREAD

**Issue by stephanielingwood** [Shippable/admiral#83]
Shippable/pm#8312

- This should call `/api/db/initialize` 
- In the UI, call `/api/workflow/initialize` when the "initialize" button is clicked, instead of `/api/db/initialize`

**Comment by ric03uec** [comment]
@stephanielingwood im not sure what this route is for. its not clear from the route description what its doing. Can we not use existing route(s) for what this is supposed to do?

**Comment by stephanielingwood** [comment]
This is the main "wrapper" route that will be called from the UI. In turn, it will call all of the workflow routes - the db init, and the route for each of the core services. This keeps the user from getting into a broken state if they refresh the page during install.
