### ISSUE TITLE
8312.3 Vault: Add vault to the initialization flow

### ISSUE THREAD

**Issue by stephanielingwood** [Shippable/admiral#84]
Shippable/pm#8312

In `/api/workflow/initialize`...
  - call GET `/api/vault`. If vault is not initialized...
  - call POST /api/vault`

In the UI:
  - add vault to the table in the initialize panel

**Comment by trriplejay** [comment]
should we be using GET `/api/vault`, or should we be using the systemConfig `secrets` object to determine if things are already initialized or not?

**Comment by trriplejay** [comment]
finished.
