### ISSUE TITLE
8312.3 RabbitMQ: Add GET /api/msg

### ISSUE THREAD

**Issue by stephanielingwood** [Shippable/admiral#90]
Shippable/pm#8312

Add `GET /api/rabbitmq`. Call this from `POST /api/initialize`. It should, similarily to Vault, get the `msg` column from systemConfigs.  If it's empty, it should save a stringified JSON object with the default values.  This object should be returned.
Default values:
```
{
  address: admiralUrl,
  amqpPort: 5672,
  adminPort: 15672,
  username: '',
  password: '',
  isSecure: false,  // amqp/amqps
  isInstalled: false,
  isInitialized: false
}
```

**Comment by ric03uec** [comment]
added GET /api/msg route which also sets defaults
