### ISSUE TITLE
add new release AMI in AWS Marketplace

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#981]
- add the AMI in AWS Marketplace for the release `v5.7.2`

**Comment by ttrahan** [comment]
AMI scan has started and will finish in ~1 hour

**Comment by ttrahan** [comment]
Scan passed. However, the prior update for v5.7.1 is still pending review and publishing by the AWS Marketplace team. I've contacted them to switch to 5.7.2 instead. Waiting on response.

**Comment by ttrahan** [comment]
No reply yet from Marketplace team. Have followed up.

**Comment by ttrahan** [comment]
This has now been published.
